
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Prp.Model
{

using System;
    using System.Collections.Generic;
    
public partial class tblApplicantInterviewMark
{

    public int applicantInterviewMarkId { get; set; }

    public int inductionId { get; set; }

    public int phaseId { get; set; }

    public int applicantId { get; set; }

    public int statusId { get; set; }

    public string comments { get; set; }

    public decimal marksExpected { get; set; }

    public decimal marksLoR { get; set; }

    public decimal marksActual { get; set; }

    public string picLoR { get; set; }

    public System.DateTime dated { get; set; }

}

}
