
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Prp.Model
{

using System;
    using System.Collections.Generic;
    
public partial class tvwAdminSuperSpeciality
{

    public int specialityId { get; set; }

    public string speciality { get; set; }

    public int superSpecialityId { get; set; }

    public string superSpeciality { get; set; }

    public bool isActive { get; set; }

    public int sortOrder { get; set; }

}

}
