
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Prp.Model
{

using System;
    using System.Collections.Generic;
    
public partial class tvwApplicantLevel3
{

    public int applicantLevel3Details { get; set; }

    public int inductionId { get; set; }

    public int phaseId { get; set; }

    public int applicantId { get; set; }

    public int typeId { get; set; }

    public string ImageCertificate { get; set; }

    public int specialityId { get; set; }

    public string specialityName { get; set; }

    public int medals { get; set; }

    public System.DateTime dated { get; set; }

}

}
